-- SQL aplicado pelo proprietário, conforme confirmação na conversa.
-- Registro versionado do DDL aplicado em public; não executar novamente.
-- Não é migration automática. O índice parcial deve ser preservado no SQL.
-- Requer plantio.id_plantio e usuarios.id_usuario integer com chave única/primária.
BEGIN;

SET LOCAL search_path TO public;

CREATE TABLE evento_plantio (
  id_evento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_plantio integer NOT NULL,
  tipo varchar(20) NOT NULL,
  modalidade varchar(20),
  motivo varchar(1000) NOT NULL,
  id_usuario integer NOT NULL,
  registrado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
  antes jsonb NOT NULL,
  depois jsonb NOT NULL,
  CONSTRAINT fk_evento_plantio FOREIGN KEY (id_plantio)
    REFERENCES plantio(id_plantio) ON DELETE RESTRICT ON UPDATE NO ACTION,
  CONSTRAINT fk_evento_usuario FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario) ON DELETE RESTRICT ON UPDATE NO ACTION,
  CONSTRAINT ck_evento_tipo CHECK (tipo IN ('ENCERRAMENTO', 'REGULARIZACAO')),
  CONSTRAINT ck_evento_modalidade CHECK (
    (tipo = 'ENCERRAMENTO' AND modalidade IS NOT NULL
      AND modalidade IN ('NORMAL', 'PERDA_TOTAL', 'PERDA_REMANESCENTE'))
    OR (tipo = 'REGULARIZACAO' AND modalidade IS NULL)
  ),
  CONSTRAINT ck_evento_motivo CHECK (char_length(btrim(motivo)) BETWEEN 5 AND 1000),
  CONSTRAINT ck_evento_snapshots CHECK (
    jsonb_typeof(antes) = 'object' AND jsonb_typeof(depois) = 'object'
  )
);

CREATE UNIQUE INDEX uq_evento_encerramento ON evento_plantio(id_plantio)
  WHERE tipo = 'ENCERRAMENTO';
CREATE INDEX ix_evento_historico ON evento_plantio(id_plantio, registrado_em, id_evento);

-- Revisar grants do usuário da aplicação: eventos devem permitir SELECT/INSERT;
-- UPDATE/DELETE de eventos não devem ser disponibilizados pela aplicação.
-- Não atribuir grants aqui sem conhecer roles/políticas do ambiente.
COMMIT;
